# Generated by Django 5.0.2 on 2024-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminresponse',
            name='needs_sending',
            field=models.BooleanField(default=True),
        ),
    ]
